### ISSUE TITLE
Local tests

### ISSUE THREAD

**Issue by NicolasDievart** [Elao/blog#18]
The make install file doesn't contain this line:
```
ansible-galaxy install -r ansible/roles.yml -p ansible/roles -f
```
Which cause a fail on `vagrant up`

Also, after the vagrant up with success, i am able to ping blog.elao.dev or the server ip, but can't connect to it with my browser (tested with Chrome, Firefox, Safari). (note that the `sudo killall -HUP mDNSResponder` command does nothing)
Maybe a known issue ? Should we also update the Readme to add the different step to test the blog locally ?

**Comment by gfaivre** [comment]
I never really work with it, I need to rework it to fix the caching issue caused by nginx proxy.

**Comment by gfaivre** [comment]
Provisioning fix by https://github.com/Elao/blog/pull/19
