### ISSUE TITLE
Interview collégiale : conception et réalisation d'API chez Elao

### ISSUE THREAD

**Issue by xavier-rdo** [Elao/blog#186]
Constat
=====

Chez Elao on a plein de talents qui ont travaillé sur API, chacun avec sa sensibilité, ses pratiques, ses préférences ...

Ma proposition
===========

Je propose donc une interview collégiale auprès des personnalités d'Elao qui ont eu à concevoir et réaliser des API. 

Intérêt d'une interview collégiale
=======================

- la diversité des opinions reflète les différentes pratiques liées aux API
- identifier des pratiques communes
- mettre en lumière les complémentarités
- offrir au lecteur des visions différentes et parfois complémentaires
- montrer qu'on a plein de talents dans l'équipe !

Propositions de questions (à affiner, compléter)  
===================================

- Votre expérience des API en quelques mots
- Un code HTTP "méconnu" que vous utilisez régulièrement
- Un header "méconnu" que vous utilisez régulièrement
- Choisir entre POST/PATCH/PUT - conseils, critères de choix ?
- Formats de sortie : JSON uniquement ?
- Gestion des erreurs, erreurs de validation : formalisme, pratiques ?
- Utilisez-vous des codes erreurs custom ?
- Une librairie de mock API pour les développeurs Frontend ?
- Le versioning d'API : quelle stratégie préconisez-vous ?
- Documenter votre API : quels outils ?
- Comment tester son API ? 
- Avez-vous des pratiques concernant les URI ? bannissez-vous sytématiquement les verbes ? Dans quels cas les utilisez-vous ?
- HATEOAS ?
- Utilisez-vous une bibliothèque-cadre pour développer vos API ? Symfony REST edition ? API-platform ?
- Normalizers/Serializers : composant Symfony ou JMSSerializer ? 
- Communication développeurs Backend/Frontend : des conseils ?
- Un ouvrage ou un site de référence à conseiller ?
- GraphQL dans tout ça ?
- Quel conseil donneriez-vous à qqn qui débute dans les API ?
- Une question que vous auriez aimé que je vous pose à propos des API ? Ou bien quelque chose à ajouter ?

Conduite  de l'interview
=================

Les "interviewés" ne répondent qu'aux questions qui les inspirent. Seront donc écartées les questions qui n'ont inspiré personne.

Selon vos préférences et vos disponibilités : entretien à chaud avec votre serviteur ou réponses par écrit, dans cette issue ...

**Comment by xavier-rdo** [comment]
![image](https://user-images.githubusercontent.com/1587796/32954221-c847bdde-cbb2-11e7-8936-d9e0014bac6c.png)

@hyvs @maximecolin @mb3rnard @ogizanagi @benji07 @supertanuki @NicolasDievart @nervo @chalasr @mb3rnard @Tom32i @cmeiller 

* Une interview collégiale sur les API, trouvez-vous ça bien|très-bien|super|nul-à-chier|super-nul-à-chier ?
* Souhaitez-vous contribuer ? Si oui, sous quelle forme : réponse écrite ou entretien oral avec bibi ?
* Quelles questions vous inspirent ? Autrement dit, auxquelles souhaitez-vous répondre ?
* Quelles questions manquent (sachant que j'ai une rubrique `quelle question auriez-vous aimé que je vous pose à propos des API) ?

**Comment by NicolasDievart** [comment]
- Une interview collégiale sur les API, trouvez-vous ça *très-bien*
- Souhaitez-vous contribuer: *oui* | sous forme: *écrite* (même si j'aimerai bien venir à Lyon pour l'occasion
- Quelles questions vous inspirent: *GraphQL*, *JSON uniquement*, *Normalizers Symfony* et quelques autres
- Quelles questions manquent: *pas d'idée dans l'immédiat*
