### ISSUE TITLE
Style sur les titres 

### ISSUE THREAD

**Issue by NicolasDievart** [Elao/blog#190]
Il y a une margin-top sur les titres qui bloquent les actions sur certains blocs de textes:

https://blog.elao.com/fr/elao/blendwebmix-2017/
les tags au dessus du titre dans article_header ne sont plus cliquables

https://blog.elao.com/fr/elao/job-frontend-developpeur-agence-lyon/
Les paragraphes avant les titres type "Aspects techniques", "Rémunération", "Vie dans l’entreprise" ne sont pas cliquables, surlignables

**Comment by Tom32i** [comment]
Ok bien vu. Ça doit être réglable à coup de `z-index`.
Je regarde ça dès que possible.
