### ISSUE TITLE
Changer le style dans le head

### ISSUE THREAD

**Issue by NicolasDievart** [Elao/blog#47]
Proposition de remplacement de:
https://github.com/Elao/blog/blob/master/themes/blog/layouts/partials/styles.html

et de mettre directement dans le head.html (https://github.com/Elao/blog/blob/master/themes/blog/layouts/partials/head.html)
`<link rel="stylesheet" href="{{ partial "i18n.html" . }}/css/main.css">`

Comme c'est le cas pour le js dans le head.html

Cela devrait permettre d'éviter d'avoir une latence entre le chargement du style et la page

**Comment by gfaivre** [comment]
Ca évite la latence, oui, mais les recos google et notamment page speed sont de charger le style en asynchrone, je sais pas trop ou placer le curser webperf pour le coup.

**Comment by xgorse** [comment]
👍  Je préfère une bonne experience utilisateur qu'un bon score PageSpeed. Ca fait bizarre le coté de la font qui arrive après
