### ISSUE TITLE
Wrong share link on Disqus panel

### ISSUE THREAD

**Issue by xgorse** [Elao/blog#63]
When you click on the share link in the Disqus panel, the page hostname is http://localhost:1313/ instead of https://blog.elao.com/

The disqus config seam good  in the source

```
var disqus_config = function () {
  this.page.url = "https://blog.elao.com/fr/dev/pourquoi-devriez-vous-utiliser-vue-js-dans-vos-projets/";  
  this.page.identifier = "pourquoi-devriez-vous-utiliser-vue-js-dans-vos-projets"; 
};
```

The 1313 port appear in the makefile for docker command

https://github.com/Elao/blog/blob/master/Makefile#L36
https://github.com/Elao/blog/blob/master/Makefile#L114

Thanks to @severin-bruhat for the  [report](https://twitter.com/severin_bruhat/status/788830232430120960?cn=bWVudGlvbg%3D%3D&refsrc=email)

**Comment by gfaivre** [comment]
Has been fixed with #64 which ignore disqus JS (dev mode). Indeed Disqus create a thread on the first page call whatever if we are on a local or public version.
